### PR TITLE
Bundle JRE 8 and use it - fix for incompatibility with newer Java versions

### PR DESCRIPTION
**Pull request by mvorisek**
fixes https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/96

notes:
- maybe not all files needs to be bundles
- still prefer to fix the compatibility with newer versions - then superseed this PR with PR that fixes it

### CODE REVIEW

**Comment by rdp** [comment]
Hmm it's tricky to include a bundled.  I might take a patch that updates
jruby though! :)

**Comment by mvorisek** [comment]
@rdp that is preffered 🚀

**Comment by mvorisek** [comment]
@rdp can you look at this in the near future? I think it is quite important issue, as JRE8 is more and more replaced with newer JREs and with the newer versions this recorded does not start, thus a lot of users are affected.

**Comment by mvorisek** [comment]
> 
> Hmm it's tricky to include a bundled. I might take a patch that updates jruby though! :)

@rdp yes, I also prefer it, would you be so kind to look at it? It is actually quite urgent, as without Java 9+ support, it won't work for most of the users. Thanks.

**Comment by rdp** [comment]
Please test https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11 thanks!

**Comment by mvorisek** [comment]
> 
> 
> Please test https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11 thanks!

I run `Setup.Screen.Capturer.Recorder.v0.12.11.exe` and the issue is gone - tested with Java 12. Many thanks, @rdp / Roger!

**Comment by rdp** [comment]
Thanks for the prods in the right direction :)

**Pull request closed without merging**
